apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hubbops
  namespace: hubbops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hubbops.local
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: hubbops-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hubbops-frontend
            port:
              number: 80
